version: '3.8'

volumes:
   minio-data:

services:
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9090"
    volumes:
      - minio-data:/data # main folder for minio to store data
    env_file: .minio-env
    ports:
      - 9000:9000 # api server
      - 9090:9090 # web console
    restart: unless-stopped
